const express = require('express');
const router = express.Router();

module.exports = (connection) => {
    // Convert connection.query to a Promise-based function with logging
    const query = (sql, params) => new Promise((resolve, reject) => {
        console.log('Executing SQL:', sql);  
        console.log('With parameters:', params);

        connection.query(sql, params, (err, results) => {
            if (err) {
                console.error('Error executing query:', err);  
                return reject(err);
            }
            resolve(results);  
        });
    });

    // Route to fetch doctor performance data
    router.get('/', async (req, res) => {
        const { doctorId, startDate, endDate } = req.query;

        try {
            console.log(`Fetching performance for doctorId: ${doctorId}, between ${startDate} and ${endDate}`);

            // 1. Unique Patients
            const uniquePatientsQuery = `
                SELECT COUNT(DISTINCT patient_id) AS uniquePatients 
                FROM visit 
                WHERE user_activated_id = ? 
                AND currentLocalTimeAssignment BETWEEN ? AND ?`;

            // 2. Total Visits
            const totalVisitsQuery = `
                SELECT COUNT(*) AS totalVisits 
                FROM visit 
                WHERE user_activated_id = ? 
                AND currentLocalTimeAssignment BETWEEN ? AND ?`;

            // 3. New Patients
            const newPatientsQuery = `
                WITH new_patients AS (
                    SELECT DISTINCT v1.patient_id
                    FROM visit AS v1
                    WHERE v1.user_activated_id = ? 
                    AND v1.currentLocalTimeAssignment BETWEEN ? AND ?
                    AND NOT EXISTS (
                        SELECT 1
                        FROM visit AS v2
                        WHERE v2.patient_id = v1.patient_id
                        AND v2.user_activated_id = v1.user_activated_id
                        AND v2.currentLocalTimeAssignment < ?
                    )
                )
                SELECT COUNT(*) AS new_patients FROM new_patients`;

            // 4. Visits Generated by New Patients
            const visitsGeneratedByNewPatientsQuery = `
                WITH new_patients AS (
                    SELECT DISTINCT v1.patient_id
                    FROM visit AS v1
                    WHERE v1.user_activated_id = ? 
                    AND v1.currentLocalTimeAssignment BETWEEN ? AND ?
                    AND NOT EXISTS (
                        SELECT 1
                        FROM visit AS v2
                        WHERE v2.patient_id = v1.patient_id
                        AND v2.user_activated_id = v1.user_activated_id
                        AND v2.currentLocalTimeAssignment < ?
                    )
                )
                SELECT COUNT(*) AS total_visits 
                FROM visit 
                WHERE patient_id IN (SELECT patient_id FROM new_patients)
                `;

            // 5. Loyal Patients
            const loyalPatientsQuery = `
                WITH previous_visits AS (
                    SELECT DISTINCT v1.patient_id
                    FROM visit AS v1
                    WHERE v1.user_activated_id = ? 
                    AND v1.currentLocalTimeAssignment < ?
                ),
                current_period_visits AS (
                    SELECT DISTINCT v2.patient_id
                    FROM visit AS v2
                    WHERE v2.user_activated_id = ? 
                    AND v2.currentLocalTimeAssignment BETWEEN ? AND ?
                )
                SELECT COUNT(DISTINCT v.patient_id) AS loyal_patients
                FROM current_period_visits AS v
                WHERE v.patient_id IN (SELECT patient_id FROM previous_visits)`;

            // 6. Follow-up Visits of Loyal Patients
            const followUpVisitsQuery = `
                WITH previous_visits AS (
                    SELECT DISTINCT v1.patient_id
                    FROM visit AS v1
                    WHERE v1.user_activated_id = ? 
                    AND v1.currentLocalTimeAssignment < ?
                ),
                first_visit_in_period AS (
                    SELECT DISTINCT v2.patient_id, MIN(v2.currentLocalTimeAssignment) AS first_visit_date
                    FROM visit AS v2
                    WHERE v2.user_activated_id = ? 
                    AND v2.currentLocalTimeAssignment BETWEEN ? AND ?
                    AND v2.patient_id IN (SELECT patient_id FROM previous_visits)
                    GROUP BY v2.patient_id
                )
                SELECT COUNT(*) AS total_followup_visits
                FROM visit
                WHERE user_activated_id = ? 
                AND currentLocalTimeAssignment > (SELECT first_visit_date FROM first_visit_in_period WHERE patient_id = visit.patient_id)
                AND patient_id IN (SELECT patient_id FROM first_visit_in_period)`;

            // 7. Hours Worked
            const hoursWorkedQuery = `
                SELECT ROUND(AVG(TIMESTAMPDIFF(MINUTE, visit.startDate, visit.endDate)),2) AS hoursWorked 
                FROM visit 
                WHERE user_activated_id = ? 
                AND currentLocalTimeAssignment BETWEEN ? AND ?`;

            // 8. Total Revenue for Acts and Consultations
            const totalRevenueQuery = `
                select sum(payment.amount) as total_paid
                from payment join visit on visit.id=payment.consultation_id 
                where user_activated_id = ?
                and visit.currentLocalTimeAssignment BETWEEN ? AND ?;`;
                // 9. Average Waiting Time
            const avgWaitingTimeQuery = `
                SELECT ROUND(AVG(TIMESTAMPDIFF(MINUTE, visit.arrivalDate, visit.startDate)),2) AS avgWaitingTime 
                FROM visit 
                WHERE user_activated_id = ? 
                AND currentLocalTimeAssignment BETWEEN ? AND ?`;

            // 10. actes 
            const actesQuery = `
                WITH visites_patients AS (
                    SELECT description1 AS acte, 
                           COUNT(visit.id) AS nb_visites, 
                           COUNT(DISTINCT dental_diagram.patient_id) AS nb_patients,
                           SUM(TIMESTAMPDIFF(MINUTE, visit.startdate, visit.enddate))/60 AS total_hours
                    FROM dental_diagram_udc 
                    JOIN dental_diagram ON dental_diagram.id = dental_diagram_udc.dental_diagram_id
                    JOIN udc ON udc.id = dental_diagram_udc.udc_id
                    JOIN visit ON visit.id = dental_diagram.consultation_id
                    WHERE user_activated_id = ?
                    AND visit.currentLocalTimeAssignment BETWEEN ? AND ?
                    GROUP BY description1
                ),
                paiements AS (
                    SELECT description1 AS acte, 
                           SUM(payment.amount) AS revenus
                    FROM dental_diagram_udc 
                    JOIN dental_diagram ON dental_diagram.id = dental_diagram_udc.dental_diagram_id
                    JOIN udc ON udc.id = dental_diagram_udc.udc_id
                    JOIN visit ON visit.id = dental_diagram.consultation_id
                    LEFT JOIN payment ON payment.consultation_id = visit.id
                    WHERE user_activated_id = ?
                    AND visit.currentLocalTimeAssignment BETWEEN ? AND ?
                    GROUP BY description1
                )
                SELECT v.acte as acte, 
                       v.nb_visites as totalActs, 
                       v.nb_patients as uniquePatients, 
                       COALESCE(p.revenus, 0) AS totalRevenue,
                        ROUND(v.total_hours,2) AS total_hours,
                       ROUND((COALESCE(p.revenus, 0) / NULLIF(v.total_hours, 0)),2) AS avg_cost_per_hour
                FROM visites_patients v
                LEFT JOIN paiements p ON v.acte = p.acte
                ORDER BY totalRevenue DESC;`

            // 11. new Patients clinic (1st visit with this doctor)
            const newPatientsClinicQuery = `SELECT COUNT(DISTINCT v1.patient_id) AS uniquePatients
                                        FROM visit AS v1
                                        WHERE v1.user_activated_id = ?
                                        AND v1.currentLocalTimeAssignment BETWEEN ? AND ?
                                        AND NOT EXISTS (
                                            SELECT 1
                                            FROM visit AS v2
                                            WHERE v2.patient_id = v1.patient_id
                                            AND v2.currentLocalTimeAssignment < ?
                                        );`;
    
            // 12. nombre de visite généré par les patients ayant fait leur premiere viste avec ce medecin
            const VisitsBynewPatientsClinicQuery=`SELECT COUNT(*) AS total_visits
                                            FROM visit AS v1
                                            WHERE v1.patient_id IN (
                                                SELECT v2.patient_id
                                                FROM visit AS v2
                                                WHERE v2.user_activated_id = ?
                                                AND v2.currentLocalTimeAssignment BETWEEN ? AND ?
                                                AND NOT EXISTS (
                                                    SELECT 1
                                                    FROM visit AS v3
                                                    WHERE v3.patient_id = v2.patient_id
                                                    AND v3.currentLocalTimeAssignment < ?
                                                )
                                            );`;
         
         // 
         const patientsPasRetourQuery =`SELECT COUNT(DISTINCT v1.patient_id) AS patients_never_returned
                                    FROM visit AS v1
                                    WHERE v1.user_activated_id = ?  -- ID du médecin spécifique
                                    AND v1.currentLocalTimeAssignment BETWEEN ? AND ?  -- Intervalle de temps pour la visite avec le médecin
                                    AND NOT EXISTS (
                                        SELECT 1
                                        FROM visit AS v2
                                        WHERE v2.patient_id = v1.patient_id
                                        AND v2.currentLocalTimeAssignment > ?  -- Pas de visites après l'intervalle
                                    );`;
            const total_hoursQuery = `SELECT  user_activated_id,ROUND(SUM(TIMESTAMPDIFF(MINUTE, visit.startDate, visit.endDate))/60,2) AS hoursWorked 
                                        FROM dental_diagram_udc 
                                        JOIN dental_diagram ON dental_diagram.id = dental_diagram_udc.dental_diagram_id
                                        JOIN udc ON udc.id = dental_diagram_udc.udc_id
                                        JOIN visit ON visit.id = dental_diagram.consultation_id
                                        where user_activated_id = ?
                                        and visit.currentLocalTimeAssignment BETWEEN ? AND ?;`;
            // Execute the queries
            const uniquePatients = await query(uniquePatientsQuery, [doctorId, startDate, endDate]);
            const totalVisits = await query(totalVisitsQuery, [doctorId, startDate, endDate]);
            const newPatients = await query(newPatientsQuery, [doctorId, startDate, endDate, startDate]);
            const visitsGeneratedByNewPatients = await query(visitsGeneratedByNewPatientsQuery, [doctorId, startDate, endDate, startDate]);
            const loyalPatients = await query(loyalPatientsQuery, [doctorId, startDate, doctorId, startDate, endDate]);
            const followUpVisits = await query(followUpVisitsQuery, [doctorId, startDate, doctorId, startDate, endDate, doctorId]);
            const hoursWorked = await query(hoursWorkedQuery, [doctorId, startDate, endDate]);
            const total_hours = await query(total_hoursQuery, [doctorId, startDate, endDate]);
            const totalRevenue = await query(totalRevenueQuery, [doctorId, startDate, endDate]);
            const avgWaitingTime = await query(avgWaitingTimeQuery, [doctorId, startDate, endDate]);
            const actes = await query(actesQuery, [doctorId, startDate, endDate,doctorId, startDate, endDate]);
            const newPatientsClinic=await query(newPatientsClinicQuery, [doctorId, startDate, endDate, startDate]);
            const VisitsBynewPatientsClinic=await query(VisitsBynewPatientsClinicQuery, [doctorId, startDate, endDate, startDate]);
            const patientsPasRetour=await query(patientsPasRetourQuery, [doctorId, startDate, endDate, endDate]);
            
           
            const hoursWorkedTotal=(hoursWorked[0].hoursWorked * totalVisits[0]?.totalVisits) / 60;
            // Handle potential division by zero for revenue per hour
            const revenuePerHour = hoursWorked[0].hoursWorked 
                ? (totalRevenue[0].total_paid / (hoursWorkedTotal)).toFixed(2)
                : 0;

            // Send the result back to the client
            res.json({
                stats: {
                uniquePatients: uniquePatients[0]?.uniquePatients || 0,
                totalVisits: totalVisits[0]?.totalVisits || 0,
                newPatients: newPatients[0]?.new_patients || 0,
                visitsGeneratedByNewPatients: visitsGeneratedByNewPatients[0]?.total_visits || 0,
                loyalPatients: loyalPatients[0]?.loyal_patients || 0,
                followUpVisits: followUpVisits[0]?.total_followup_visits || 0,
                hoursWorked: hoursWorked[0]?.hoursWorked || 0,
                totalPaidForConsultations: totalRevenue[0]?.total_paid || 0,
                revenuePerHour: revenuePerHour,
                avgWaitingTime: avgWaitingTime[0]?.avgWaitingTime || 0,
                patientsPremiereVisite: newPatientsClinic[0]?.uniquePatients || 0,
                VisitsBynewPatientsClinic:VisitsBynewPatientsClinic[0]?.total_visits || 0,
                total_hours:total_hours[0]?.hoursWorked ||0,
                patientsPasRetour: patientsPasRetour[0]?.patients_never_returned || 0
                },
                actes: actes,
                
            });
        } catch (error) {
            console.error('Erreur lors de la récupération des données du médecin:', error);
            res.status(500).json({
                error: 'An error occurred while fetching the doctor performance data.',
                details: error.message
            });
        }
    });

    // Route to fetch available doctors
    router.get('/api/doctors', async (req, res) => {
        try {
            const doctorsQuery = 'SELECT id, firstName, lastName FROM user WHERE role = "doctor" and user.enabled=0';
            const doctors = await query(doctorsQuery);
            res.json(doctors);
        } catch (error) {
            console.error('Erreur lors de la récupération des médecins:', error);
            res.status(500).json({
                error: 'An error occurred while fetching the doctors data.',
                details: error.message
            });
        }
    });

    return router;
};
