const express = require('express');
const router = express.Router();
const { DateTime } = require('luxon'); // Assurez-vous d'avoir installé Luxon

module.exports = (connection) => {
    // Convertit connection.query en fonction basée sur les Promesses avec journalisation
    const query = (sql, params) => new Promise((resolve, reject) => {
        console.log('Exécution de la requête SQL:', sql);
        console.log('Avec les paramètres:', params);
        connection.query(sql, params, (err, results) => {
            if (err) {
                console.error('Erreur lors de l\'exécution de la requête:', err);
                return reject(err);
            }
            resolve(results);
        });
    });

    // Nouvelle route pour récupérer les statistiques mensuelles
    router.get('/', async (req, res) => {
        const { doctorId, startDate, endDate } = req.query;

        try {
            console.log(`Récupération des statistiques mensuelles pour le médecin ID: ${doctorId}, entre ${startDate} et ${endDate}`);

            // Parse les dates de début et de fin en utilisant Luxon
            const start = DateTime.fromISO(startDate).startOf('month');
            const end = DateTime.fromISO(endDate).endOf('month');

            // Génère un tableau des mois entre startDate et endDate
            const months = [];
            let current = start;
            while (current <= end) {
                months.push(current.toFormat('yyyy-MM'));
                current = current.plus({ months: 1 });
            }

            const result = {};

            for (const month of months) {
                // Définit les dates de début et de fin pour le mois
                const startDateMonth = DateTime.fromFormat(month, 'yyyy-MM').startOf('month').toISODate();
                const endDateMonth = DateTime.fromFormat(month, 'yyyy-MM').endOf('month').toISODate();

                // Ajuste les requêtes pour le mois en utilisant vos requêtes originales avec les paramètres de date ajustés

                // 1. Unique Patients
                const uniquePatientsQuery = `
                    SELECT COUNT(DISTINCT patient_id) AS uniquePatients 
                    FROM visit 
                    WHERE user_activated_id = ? 
                    AND currentLocalTimeAssignment BETWEEN ? AND ?`;

                // 2. Total Visits
                const totalVisitsQuery = `
                    SELECT COUNT(*) AS totalVisits 
                    FROM visit 
                    WHERE user_activated_id = ? 
                    AND currentLocalTimeAssignment BETWEEN ? AND ?`;

                // 3. New Patients
                const newPatientsQuery = `
                    WITH new_patients AS (
                        SELECT DISTINCT v1.patient_id
                        FROM visit AS v1
                        WHERE v1.user_activated_id = ? 
                        AND v1.currentLocalTimeAssignment BETWEEN ? AND ?
                        AND NOT EXISTS (
                            SELECT 1
                            FROM visit AS v2
                            WHERE v2.patient_id = v1.patient_id
                            AND v2.user_activated_id = v1.user_activated_id
                            AND v2.currentLocalTimeAssignment < ?
                        )
                    )
                    SELECT COUNT(*) AS new_patients FROM new_patients`;

                // 4. Visits Generated by New Patients
                const visitsGeneratedByNewPatientsQuery = `
                    WITH new_patients AS (
                        SELECT DISTINCT v1.patient_id
                        FROM visit AS v1
                        WHERE v1.user_activated_id = ? 
                        AND v1.currentLocalTimeAssignment BETWEEN ? AND ?
                        AND NOT EXISTS (
                            SELECT 1
                            FROM visit AS v2
                            WHERE v2.patient_id = v1.patient_id
                            AND v2.user_activated_id = v1.user_activated_id
                            AND v2.currentLocalTimeAssignment < ?
                        )
                    )
                    SELECT COUNT(*) AS total_visits 
                    FROM visit 
                    WHERE patient_id IN (SELECT patient_id FROM new_patients)`;

                // 5. Loyal Patients
                const loyalPatientsQuery = `
                    WITH previous_visits AS (
                        SELECT DISTINCT v1.patient_id
                        FROM visit AS v1
                        WHERE v1.user_activated_id = ? 
                        AND v1.currentLocalTimeAssignment < ?
                    ),
                    current_period_visits AS (
                        SELECT DISTINCT v2.patient_id
                        FROM visit AS v2
                        WHERE v2.user_activated_id = ? 
                        AND v2.currentLocalTimeAssignment BETWEEN ? AND ?
                    )
                    SELECT COUNT(DISTINCT v.patient_id) AS loyal_patients
                    FROM current_period_visits AS v
                    WHERE v.patient_id IN (SELECT patient_id FROM previous_visits)`;

                // 6. Follow-up Visits of Loyal Patients
                const followUpVisitsQuery = `
                    WITH previous_visits AS (
                        SELECT DISTINCT v1.patient_id
                        FROM visit AS v1
                        WHERE v1.user_activated_id = ? 
                        AND v1.currentLocalTimeAssignment < ?
                    ),
                    first_visit_in_period AS (
                        SELECT DISTINCT v2.patient_id, MIN(v2.currentLocalTimeAssignment) AS first_visit_date
                        FROM visit AS v2
                        WHERE v2.user_activated_id = ? 
                        AND v2.currentLocalTimeAssignment BETWEEN ? AND ?
                        AND v2.patient_id IN (SELECT patient_id FROM previous_visits)
                        GROUP BY v2.patient_id
                    )
                    SELECT COUNT(*) AS total_followup_visits
                    FROM visit
                    WHERE user_activated_id = ? 
                    AND currentLocalTimeAssignment > (SELECT first_visit_date FROM first_visit_in_period WHERE patient_id = visit.patient_id)
                    AND patient_id IN (SELECT patient_id FROM first_visit_in_period)`;

                // 7. Hours Worked
                const hoursWorkedQuery = `
                    SELECT ROUND(AVG(TIMESTAMPDIFF(MINUTE, visit.startDate, visit.endDate)),2) AS hoursWorked 
                    FROM visit 
                    WHERE user_activated_id = ? 
                    AND currentLocalTimeAssignment BETWEEN ? AND ?`;

                // 8. Total Revenue for Acts and Consultations
                const totalRevenueQuery = `
                    SELECT SUM(payment.amount) AS total_paid
                    FROM payment JOIN visit ON visit.id=payment.consultation_id 
                    WHERE user_activated_id = ?
                    AND visit.currentLocalTimeAssignment BETWEEN ? AND ?`;

                // 9. Average Waiting Time
                const avgWaitingTimeQuery = `
                    SELECT ROUND(AVG(TIMESTAMPDIFF(MINUTE, visit.arrivalDate, visit.startDate)),2) AS avgWaitingTime 
                    FROM visit 
                    WHERE user_activated_id = ? 
                    AND currentLocalTimeAssignment BETWEEN ? AND ?`;

                // 10. Actes
                const actesQuery = `
                    WITH visites_patients AS (
                        SELECT description1 AS acte, 
                               COUNT(DISTINCT visit.id) AS nb_visites, 
                               COUNT(DISTINCT dental_diagram.patient_id) AS nb_patients,
                               SUM(TIMESTAMPDIFF(MINUTE, visit.startdate, visit.enddate))/60 AS total_hours
                        FROM dental_diagram_udc 
                        JOIN dental_diagram ON dental_diagram.id = dental_diagram_udc.dental_diagram_id
                        JOIN udc ON udc.id = dental_diagram_udc.udc_id
                        JOIN visit ON visit.id = dental_diagram.consultation_id
                        WHERE user_activated_id = ?
                        AND visit.currentLocalTimeAssignment BETWEEN ? AND ?
                        GROUP BY description1
                    ),
                    paiements AS (
                        SELECT description1 AS acte, 
                               SUM(payment.amount) AS revenus
                        FROM dental_diagram_udc 
                        JOIN dental_diagram ON dental_diagram.id = dental_diagram_udc.dental_diagram_id
                        JOIN udc ON udc.id = dental_diagram_udc.udc_id
                        JOIN visit ON visit.id = dental_diagram.consultation_id
                        LEFT JOIN payment ON payment.consultation_id = visit.id
                        WHERE user_activated_id = ?
                        AND visit.currentLocalTimeAssignment BETWEEN ? AND ?
                        GROUP BY description1
                    )
                    SELECT v.acte as acte, 
                           v.nb_visites as totalActs, 
                           v.nb_patients as uniquePatients, 
                           COALESCE(p.revenus, 0) AS totalRevenue,
                           ROUND(v.total_hours,2) AS total_hours,
                           ROUND((COALESCE(p.revenus, 0) / NULLIF(v.total_hours, 0)),2) AS avg_cost_per_hour
                    FROM visites_patients v
                    LEFT JOIN paiements p ON v.acte = p.acte
                    ORDER BY totalRevenue DESC`;

                // 11. New Patients Clinic (1st visit to the clinic)
                const newPatientsClinicQuery = `
                    SELECT COUNT(DISTINCT v1.patient_id) AS uniquePatients
                    FROM visit AS v1
                    WHERE v1.user_activated_id = ?
                    AND v1.currentLocalTimeAssignment BETWEEN ? AND ?
                    AND NOT EXISTS (
                        SELECT 1
                        FROM visit AS v2
                        WHERE v2.patient_id = v1.patient_id
                        AND v2.currentLocalTimeAssignment < ?
                    )`;

                // 12. Visits by Patients with First Visit to the Clinic
                const visitsByNewPatientsClinicQuery = `
                    SELECT COUNT(*) AS total_visits
                    FROM visit AS v1
                    WHERE v1.patient_id IN (
                        SELECT v2.patient_id
                        FROM visit AS v2
                        WHERE v2.user_activated_id = ?
                        AND v2.currentLocalTimeAssignment BETWEEN ? AND ?
                        AND NOT EXISTS (
                            SELECT 1
                            FROM visit AS v3
                            WHERE v3.patient_id = v2.patient_id
                            AND v3.currentLocalTimeAssignment < ?
                        )
                    )`;

                // 13. Patients Who Never Returned
                const patientsPasRetourQuery = `
                    SELECT COUNT(DISTINCT v1.patient_id) AS patients_never_returned
                    FROM visit AS v1
                    WHERE v1.user_activated_id = ?
                    AND v1.currentLocalTimeAssignment BETWEEN ? AND ?
                    AND NOT EXISTS (
                        SELECT 1
                        FROM visit AS v2
                        WHERE v2.patient_id = v1.patient_id
                        AND v2.currentLocalTimeAssignment > ?
                    )`;

                // 14. Total Hours
                const totalHoursQuery = `
                    SELECT user_activated_id,
                           ROUND(SUM(TIMESTAMPDIFF(MINUTE, visit.startDate, visit.endDate))/60,2) AS hoursWorked 
                    FROM dental_diagram_udc 
                    JOIN dental_diagram ON dental_diagram.id = dental_diagram_udc.dental_diagram_id
                    JOIN udc ON udc.id = dental_diagram_udc.udc_id
                    JOIN visit ON visit.id = dental_diagram.consultation_id
                    WHERE user_activated_id = ?
                    AND visit.currentLocalTimeAssignment BETWEEN ? AND ?`;

                // Exécute les requêtes pour le mois
                const [
                    uniquePatients,
                    totalVisits,
                    newPatients,
                    visitsGeneratedByNewPatients,
                    loyalPatients,
                    followUpVisits,
                    hoursWorked,
                    totalHours,
                    totalRevenue,
                    avgWaitingTime,
                    actes,
                    newPatientsClinic,
                    visitsByNewPatientsClinic,
                    patientsPasRetour,
                ] = await Promise.all([
                    query(uniquePatientsQuery, [doctorId, startDateMonth, endDateMonth]),
                    query(totalVisitsQuery, [doctorId, startDateMonth, endDateMonth]),
                    query(newPatientsQuery, [doctorId, startDateMonth, endDateMonth, startDateMonth]),
                    query(visitsGeneratedByNewPatientsQuery, [doctorId, startDateMonth, endDateMonth, startDateMonth]),
                    query(loyalPatientsQuery, [doctorId, startDateMonth, doctorId, startDateMonth, endDateMonth]),
                    query(followUpVisitsQuery, [doctorId, startDateMonth, doctorId, startDateMonth, endDateMonth, doctorId]),
                    query(hoursWorkedQuery, [doctorId, startDateMonth, endDateMonth]),
                    query(totalHoursQuery, [doctorId, startDateMonth, endDateMonth]),
                    query(totalRevenueQuery, [doctorId, startDateMonth, endDateMonth]),
                    query(avgWaitingTimeQuery, [doctorId, startDateMonth, endDateMonth]),
                    query(actesQuery, [doctorId, startDateMonth, endDateMonth, doctorId, startDateMonth, endDateMonth]),
                    query(newPatientsClinicQuery, [doctorId, startDateMonth, endDateMonth, startDateMonth]),
                    query(visitsByNewPatientsClinicQuery, [doctorId, startDateMonth, endDateMonth, startDateMonth]),
                    query(patientsPasRetourQuery, [doctorId, startDateMonth, endDateMonth, endDateMonth]),
                ]);

                // Calcule hoursWorkedTotal et revenuePerHour
                const totalVisitsCount = totalVisits[0]?.totalVisits || 0;
                const hoursWorkedValue = hoursWorked[0]?.hoursWorked || 0;
                const totalRevenueValue = totalRevenue[0]?.total_paid || 0;

                const hoursWorkedTotal = (hoursWorkedValue * totalVisitsCount) / 60;
                const revenuePerHour = hoursWorkedTotal > 0
                    ? (totalRevenueValue / hoursWorkedTotal).toFixed(2)
                    : '0.00';

                // Stocke les résultats pour le mois
                result[month] = {
                    stats: {
                        uniquePatients: uniquePatients[0]?.uniquePatients || 0,
                        totalVisits: totalVisitsCount,
                        newPatients: newPatients[0]?.new_patients || 0,
                        visitsGeneratedByNewPatients: visitsGeneratedByNewPatients[0]?.total_visits || 0,
                        loyalPatients: loyalPatients[0]?.loyal_patients || 0,
                        followUpVisits: followUpVisits[0]?.total_followup_visits || 0,
                        visitDuration: hoursWorkedValue,
                        totalPaidForConsultations: totalRevenueValue,
                        revenuePerHour: revenuePerHour,
                        avgWaitingTime: avgWaitingTime[0]?.avgWaitingTime || 0,
                        patientsPremiereVisite: newPatientsClinic[0]?.uniquePatients || 0,
                        VisitsByNewPatientsClinic: visitsByNewPatientsClinic[0]?.total_visits || 0,
                        total_hours: totalHours[0]?.hoursWorked || 0,
                        patientsPasRetour: patientsPasRetour[0]?.patients_never_returned || 0
                    },
                    actes: actes,
                };
            }

            // Envoie le résultat combiné au client
            res.json(result);

        } catch (error) {
            console.error('Erreur lors de la récupération des statistiques mensuelles:', error);
            res.status(500).json({
                error: 'Une erreur est survenue lors de la récupération des statistiques mensuelles.',
                details: error.message,
            });
        }
    });

    return router;
};
